<?php

use App\CarManufacturer;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarModelSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $models = [
            ['manufacturer' => 'Acura','name' => 'CL'],
            ['manufacturer' => 'Acura','name' => 'EL'],
            ['manufacturer' => 'Acura','name' => 'ILX'],
            ['manufacturer' => 'Acura','name' => 'Integra'],
            ['manufacturer' => 'Acura','name' => 'MDX'],
            ['manufacturer' => 'Acura','name' => 'NSX'],
            ['manufacturer' => 'Acura','name' => 'RDX'],
            ['manufacturer' => 'Acura','name' => 'RL'],
            ['manufacturer' => 'Acura','name' => 'RLX'],
            ['manufacturer' => 'Acura','name' => 'RSX'],
            ['manufacturer' => 'Acura','name' => 'TL'],
            ['manufacturer' => 'Acura','name' => 'TLX'],
            ['manufacturer' => 'Acura','name' => 'TSX'],
            ['manufacturer' => 'Acura','name' => 'ZDX'],
            ['manufacturer' => 'Alfa Romeo','name' => '146'],
            ['manufacturer' => 'Alfa Romeo','name' => '147'],
            ['manufacturer' => 'Alfa Romeo','name' => '147 GTA'],
            ['manufacturer' => 'Alfa Romeo','name' => '156'],
            ['manufacturer' => 'Alfa Romeo','name' => '156 GTA'],
            ['manufacturer' => 'Alfa Romeo','name' => '159'],
            ['manufacturer' => 'Alfa Romeo','name' => '166'],
            ['manufacturer' => 'Alfa Romeo','name' => '4C'],
            ['manufacturer' => 'Alfa Romeo','name' => '8C Competizione'],
            ['manufacturer' => 'Alfa Romeo','name' => 'Brera'],
            ['manufacturer' => 'Alfa Romeo','name' => 'Giulia'],
            ['manufacturer' => 'Alfa Romeo','name' => 'Giulietta'],
            ['manufacturer' => 'Alfa Romeo','name' => 'GT'],
            ['manufacturer' => 'Alfa Romeo','name' => 'GTV'],
            ['manufacturer' => 'Alfa Romeo','name' => 'MiTo'],
            ['manufacturer' => 'Alfa Romeo','name' => 'Spider'],
            ['manufacturer' => 'Alfa Romeo','name' => 'Stelvio'],
            ['manufacturer' => 'Aston Martin','name' => 'Cygnet'],
            ['manufacturer' => 'Aston Martin','name' => 'DB11'],
            ['manufacturer' => 'Aston Martin','name' => 'DB9'],
            ['manufacturer' => 'Aston Martin','name' => 'DBS'],
            ['manufacturer' => 'Aston Martin','name' => 'DBS Violante'],
            ['manufacturer' => 'Aston Martin','name' => 'DBX'],
            ['manufacturer' => 'Aston Martin','name' => 'Rapide'],
            ['manufacturer' => 'Aston Martin','name' => 'V12 Vantage'],
            ['manufacturer' => 'Aston Martin','name' => 'V8 Vantage'],
            ['manufacturer' => 'Aston Martin','name' => 'Valkyrie'],
            ['manufacturer' => 'Aston Martin','name' => 'Vanquish'],
            ['manufacturer' => 'Aston Martin','name' => 'Virage'],
            ['manufacturer' => 'Aston Martin','name' => 'Zagato Coupe'],
            ['manufacturer' => 'Audi','name' => 'A1'],
            ['manufacturer' => 'Audi','name' => 'A2'],
            ['manufacturer' => 'Audi','name' => 'A3'],
            ['manufacturer' => 'Audi','name' => 'A4'],
            ['manufacturer' => 'Audi','name' => 'A4 Allroad Quattro'],
            ['manufacturer' => 'Audi','name' => 'A5'],
            ['manufacturer' => 'Audi','name' => 'A6'],
            ['manufacturer' => 'Audi','name' => 'A7'],
            ['manufacturer' => 'Audi','name' => 'A8'],
            ['manufacturer' => 'Audi','name' => 'Allroad'],
            ['manufacturer' => 'Audi','name' => 'Q2'],
            ['manufacturer' => 'Audi','name' => 'Q3'],
            ['manufacturer' => 'Audi','name' => 'Q5'],
            ['manufacturer' => 'Audi','name' => 'Q7'],
            ['manufacturer' => 'Audi','name' => 'Q8'],
            ['manufacturer' => 'Audi','name' => 'R8'],
            ['manufacturer' => 'Audi','name' => 'RS Q3'],
            ['manufacturer' => 'Audi','name' => 'RS3'],
            ['manufacturer' => 'Audi','name' => 'RS4'],
            ['manufacturer' => 'Audi','name' => 'RS5'],
            ['manufacturer' => 'Audi','name' => 'RS6'],
            ['manufacturer' => 'Audi','name' => 'RS7'],
            ['manufacturer' => 'Audi','name' => 'S3'],
            ['manufacturer' => 'Audi','name' => 'S4'],
            ['manufacturer' => 'Audi','name' => 'S5'],
            ['manufacturer' => 'Audi','name' => 'S6'],
            ['manufacturer' => 'Audi','name' => 'S7'],
            ['manufacturer' => 'Audi','name' => 'S8'],
            ['manufacturer' => 'Audi','name' => 'SQ2'],
            ['manufacturer' => 'Audi','name' => 'SQ5'],
            ['manufacturer' => 'Audi','name' => 'SQ7'],
            ['manufacturer' => 'Audi','name' => 'SQ8'],
            ['manufacturer' => 'Audi','name' => 'TT'],
            ['manufacturer' => 'Audi','name' => 'TT RS'],
            ['manufacturer' => 'Audi','name' => 'TTS'],
            ['manufacturer' => 'Bentley','name' => 'Arnage'],
            ['manufacturer' => 'Bentley','name' => 'Azure'],
            ['manufacturer' => 'Bentley','name' => 'Bentayga'],
            ['manufacturer' => 'Bentley','name' => 'Brooklands'],
            ['manufacturer' => 'Bentley','name' => 'Continental'],
            ['manufacturer' => 'Bentley','name' => 'Continental Flying Spur'],
            ['manufacturer' => 'Bentley','name' => 'Continental GT'],
            ['manufacturer' => 'Bentley','name' => 'Flying Spur'],
            ['manufacturer' => 'Bentley','name' => 'Mulsanne'],
            ['manufacturer' => 'BMW','name' => '1 series'],
            ['manufacturer' => 'BMW','name' => '2 series'],
            ['manufacturer' => 'BMW','name' => '3 series'],
            ['manufacturer' => 'BMW','name' => '4 series'],
            ['manufacturer' => 'BMW','name' => '5 series'],
            ['manufacturer' => 'BMW','name' => '6 series'],
            ['manufacturer' => 'BMW','name' => '7 series'],
            ['manufacturer' => 'BMW','name' => '8 series'],
            ['manufacturer' => 'BMW','name' => 'i3'],
            ['manufacturer' => 'BMW','name' => 'i8'],
            ['manufacturer' => 'BMW','name' => 'M2'],
            ['manufacturer' => 'BMW','name' => 'M3'],
            ['manufacturer' => 'BMW','name' => 'M4'],
            ['manufacturer' => 'BMW','name' => 'M5'],
            ['manufacturer' => 'BMW','name' => 'M6'],
            ['manufacturer' => 'BMW','name' => 'X1'],
            ['manufacturer' => 'BMW','name' => 'X2'],
            ['manufacturer' => 'BMW','name' => 'X3'],
            ['manufacturer' => 'BMW','name' => 'X3 M'],
            ['manufacturer' => 'BMW','name' => 'X4'],
            ['manufacturer' => 'BMW','name' => 'X4 M'],
            ['manufacturer' => 'BMW','name' => 'X5'],
            ['manufacturer' => 'BMW','name' => 'X5 M'],
            ['manufacturer' => 'BMW','name' => 'X6'],
            ['manufacturer' => 'BMW','name' => 'X6 M'],
            ['manufacturer' => 'BMW','name' => 'X7'],
            ['manufacturer' => 'BMW','name' => 'Z3'],
            ['manufacturer' => 'BMW','name' => 'Z4'],
            ['manufacturer' => 'BMW','name' => 'Z8'],
            ['manufacturer' => 'Brilliance','name' => 'H230'],
            ['manufacturer' => 'Brilliance','name' => 'V3'],
            ['manufacturer' => 'Brilliance','name' => 'V5'],
            ['manufacturer' => 'Buick','name' => 'Century'],
            ['manufacturer' => 'Buick','name' => 'Enclave'],
            ['manufacturer' => 'Buick','name' => 'Envision'],
            ['manufacturer' => 'Buick','name' => 'La Crosse'],
            ['manufacturer' => 'Buick','name' => 'Le Sabre'],
            ['manufacturer' => 'Buick','name' => 'Lucerne'],
            ['manufacturer' => 'Buick','name' => 'Park Avenue'],
            ['manufacturer' => 'Buick','name' => 'Rainier'],
            ['manufacturer' => 'Buick','name' => 'Regal'],
            ['manufacturer' => 'Buick','name' => 'Rendezvouz'],
            ['manufacturer' => 'Buick','name' => 'Terraza'],
            ['manufacturer' => 'Buick','name' => 'Verano'],
            ['manufacturer' => 'BYD','name' => 'Qin'],
            ['manufacturer' => 'Cadillac','name' => 'ATS'],
            ['manufacturer' => 'Cadillac','name' => 'ATS-V'],
            ['manufacturer' => 'Cadillac','name' => 'BLS'],
            ['manufacturer' => 'Cadillac','name' => 'CT6'],
            ['manufacturer' => 'Cadillac','name' => 'CTS'],
            ['manufacturer' => 'Cadillac','name' => 'De Ville'],
            ['manufacturer' => 'Cadillac','name' => 'DTS'],
            ['manufacturer' => 'Cadillac','name' => 'Eldorado'],
            ['manufacturer' => 'Cadillac','name' => 'ELR'],
            ['manufacturer' => 'Cadillac','name' => 'Escalade'],
            ['manufacturer' => 'Cadillac','name' => 'Seville'],
            ['manufacturer' => 'Cadillac','name' => 'SRX'],
            ['manufacturer' => 'Cadillac','name' => 'STS'],
            ['manufacturer' => 'Cadillac','name' => 'XLR'],
            ['manufacturer' => 'Cadillac','name' => 'XT4'],
            ['manufacturer' => 'Cadillac','name' => 'XT5'],
            ['manufacturer' => 'Cadillac','name' => 'XT6'],
            ['manufacturer' => 'Cadillac','name' => 'XTS'],
            ['manufacturer' => 'Changan','name' => 'CS35'],
            ['manufacturer' => 'Changan','name' => 'CS35 Plus'],
            ['manufacturer' => 'Changan','name' => 'CS55'],
            ['manufacturer' => 'Changan','name' => 'CS75'],
            ['manufacturer' => 'Changan','name' => 'Eado'],
            ['manufacturer' => 'Changan','name' => 'Raeton'],
            ['manufacturer' => 'Chery','name' => 'Amulet'],
            ['manufacturer' => 'Chery','name' => 'Arrizo 7'],
            ['manufacturer' => 'Chery','name' => 'Bonus'],
            ['manufacturer' => 'Chery','name' => 'Bonus 3'],
            ['manufacturer' => 'Chery','name' => 'CrossEastar'],
            ['manufacturer' => 'Chery','name' => 'Eastar'],
            ['manufacturer' => 'Chery','name' => 'Fora'],
            ['manufacturer' => 'Chery','name' => 'IndiS'],
            ['manufacturer' => 'Chery','name' => 'Kimo'],
            ['manufacturer' => 'Chery','name' => 'M11'],
            ['manufacturer' => 'Chery','name' => 'QQ'],
            ['manufacturer' => 'Chery','name' => 'QQ6'],
            ['manufacturer' => 'Chery','name' => 'Tiggo'],
            ['manufacturer' => 'Chery','name' => 'Tiggo 3'],
            ['manufacturer' => 'Chery','name' => 'Tiggo 4'],
            ['manufacturer' => 'Chery','name' => 'Tiggo 5'],
            ['manufacturer' => 'Chery','name' => 'Tiggo 7'],
            ['manufacturer' => 'Chery','name' => 'Very'],
            ['manufacturer' => 'Chevrolet','name' => 'Astro'],
            ['manufacturer' => 'Chevrolet','name' => 'Avalanche'],
            ['manufacturer' => 'Chevrolet','name' => 'Aveo'],
            ['manufacturer' => 'Chevrolet','name' => 'Blazer'],
            ['manufacturer' => 'Chevrolet','name' => 'Camaro'],
            ['manufacturer' => 'Chevrolet','name' => 'Captiva'],
            ['manufacturer' => 'Chevrolet','name' => 'Cavalier'],
            ['manufacturer' => 'Chevrolet','name' => 'Cobalt'],
            ['manufacturer' => 'Chevrolet','name' => 'Colorado'],
            ['manufacturer' => 'Chevrolet','name' => 'Corvette'],
            ['manufacturer' => 'Chevrolet','name' => 'Cruze'],
            ['manufacturer' => 'Chevrolet','name' => 'Epica'],
            ['manufacturer' => 'Chevrolet','name' => 'Equinox'],
            ['manufacturer' => 'Chevrolet','name' => 'Express'],
            ['manufacturer' => 'Chevrolet','name' => 'HHR'],
            ['manufacturer' => 'Chevrolet','name' => 'Impala'],
            ['manufacturer' => 'Chevrolet','name' => 'Lacetti'],
            ['manufacturer' => 'Chevrolet','name' => 'Lanos'],
            ['manufacturer' => 'Chevrolet','name' => 'Malibu'],
            ['manufacturer' => 'Chevrolet','name' => 'Monte Carlo'],
            ['manufacturer' => 'Chevrolet','name' => 'Niva'],
            ['manufacturer' => 'Chevrolet','name' => 'Orlando'],
            ['manufacturer' => 'Chevrolet','name' => 'Rezzo'],
            ['manufacturer' => 'Chevrolet','name' => 'Silverado'],
            ['manufacturer' => 'Chevrolet','name' => 'Spark'],
            ['manufacturer' => 'Chevrolet','name' => 'SSR'],
            ['manufacturer' => 'Chevrolet','name' => 'Suburban'],
            ['manufacturer' => 'Chevrolet','name' => 'Tahoe'],
            ['manufacturer' => 'Chevrolet','name' => 'TrailBlazer'],
            ['manufacturer' => 'Chevrolet','name' => 'Traverse'],
            ['manufacturer' => 'Chevrolet','name' => 'Trax'],
            ['manufacturer' => 'Chevrolet','name' => 'Uplander'],
            ['manufacturer' => 'Chevrolet','name' => 'Venture'],
            ['manufacturer' => 'Chrysler','name' => '200'],
            ['manufacturer' => 'Chrysler','name' => '300'],
            ['manufacturer' => 'Chrysler','name' => '300M'],
            ['manufacturer' => 'Chrysler','name' => 'Aspen'],
            ['manufacturer' => 'Chrysler','name' => 'Concorde'],
            ['manufacturer' => 'Chrysler','name' => 'Crossfire'],
            ['manufacturer' => 'Chrysler','name' => 'Grand Voyager'],
            ['manufacturer' => 'Chrysler','name' => 'Pacifica'],
            ['manufacturer' => 'Chrysler','name' => 'PT Cruiser'],
            ['manufacturer' => 'Chrysler','name' => 'Sebring'],
            ['manufacturer' => 'Chrysler','name' => 'Town & Country'],
            ['manufacturer' => 'Chrysler','name' => 'Voyager'],
            ['manufacturer' => 'Citroen','name' => 'Berlingo'],
            ['manufacturer' => 'Citroen','name' => 'C-Crosser'],
            ['manufacturer' => 'Citroen','name' => 'C-Elysee'],
            ['manufacturer' => 'Citroen','name' => 'C1'],
            ['manufacturer' => 'Citroen','name' => 'C2'],
            ['manufacturer' => 'Citroen','name' => 'C3'],
            ['manufacturer' => 'Citroen','name' => 'C3 Aircross'],
            ['manufacturer' => 'Citroen','name' => 'C3 Picasso'],
            ['manufacturer' => 'Citroen','name' => 'C3 Pluriel'],
            ['manufacturer' => 'Citroen','name' => 'C4'],
            ['manufacturer' => 'Citroen','name' => 'C4 Aircross'],
            ['manufacturer' => 'Citroen','name' => 'C4 Cactus'],
            ['manufacturer' => 'Citroen','name' => 'C4 Picasso'],
            ['manufacturer' => 'Citroen','name' => 'C5'],
            ['manufacturer' => 'Citroen','name' => 'C6'],
            ['manufacturer' => 'Citroen','name' => 'C8'],
            ['manufacturer' => 'Citroen','name' => 'DS 7 Crossback'],
            ['manufacturer' => 'Citroen','name' => 'DS3'],
            ['manufacturer' => 'Citroen','name' => 'DS4'],
            ['manufacturer' => 'Citroen','name' => 'DS5'],
            ['manufacturer' => 'Citroen','name' => 'Grand C4 Picasso'],
            ['manufacturer' => 'Citroen','name' => 'Jumpy'],
            ['manufacturer' => 'Citroen','name' => 'Nemo'],
            ['manufacturer' => 'Citroen','name' => 'Saxo'],
            ['manufacturer' => 'Citroen','name' => 'Spacetourer'],
            ['manufacturer' => 'Citroen','name' => 'Xsara'],
            ['manufacturer' => 'Citroen','name' => 'Xsara Picasso'],
            ['manufacturer' => 'Daewoo','name' => 'Evanda'],
            ['manufacturer' => 'Daewoo','name' => 'Kalos'],
            ['manufacturer' => 'Daewoo','name' => 'Leganza'],
            ['manufacturer' => 'Daewoo','name' => 'Magnus'],
            ['manufacturer' => 'Daewoo','name' => 'Matiz'],
            ['manufacturer' => 'Daewoo','name' => 'Nexia'],
            ['manufacturer' => 'Daewoo','name' => 'Nubira'],
            ['manufacturer' => 'Daihatsu','name' => 'Applause'],
            ['manufacturer' => 'Daihatsu','name' => 'Cast'],
            ['manufacturer' => 'Daihatsu','name' => 'Copen'],
            ['manufacturer' => 'Daihatsu','name' => 'Cuore'],
            ['manufacturer' => 'Daihatsu','name' => 'Gran Move'],
            ['manufacturer' => 'Daihatsu','name' => 'Luxio'],
            ['manufacturer' => 'Daihatsu','name' => 'Materia'],
            ['manufacturer' => 'Daihatsu','name' => 'Mebius'],
            ['manufacturer' => 'Daihatsu','name' => 'Move'],
            ['manufacturer' => 'Daihatsu','name' => 'Rocky'],
            ['manufacturer' => 'Daihatsu','name' => 'Sirion'],
            ['manufacturer' => 'Daihatsu','name' => 'Terios'],
            ['manufacturer' => 'Daihatsu','name' => 'Trevis'],
            ['manufacturer' => 'Daihatsu','name' => 'YRV'],
            ['manufacturer' => 'Datsun','name' => 'mi-DO'],
            ['manufacturer' => 'Datsun','name' => 'on-DO'],
            ['manufacturer' => 'Dodge','name' => 'Avenger'],
            ['manufacturer' => 'Dodge','name' => 'Caliber'],
            ['manufacturer' => 'Dodge','name' => 'Caliber SRT4'],
            ['manufacturer' => 'Dodge','name' => 'Caravan'],
            ['manufacturer' => 'Dodge','name' => 'Challenger'],
            ['manufacturer' => 'Dodge','name' => 'Charger'],
            ['manufacturer' => 'Dodge','name' => 'Dakota'],
            ['manufacturer' => 'Dodge','name' => 'Dart'],
            ['manufacturer' => 'Dodge','name' => 'Durango'],
            ['manufacturer' => 'Dodge','name' => 'Intrepid'],
            ['manufacturer' => 'Dodge','name' => 'Journey'],
            ['manufacturer' => 'Dodge','name' => 'Magnum'],
            ['manufacturer' => 'Dodge','name' => 'Neon'],
            ['manufacturer' => 'Dodge','name' => 'Nitro'],
            ['manufacturer' => 'Dodge','name' => 'Ram 1500'],
            ['manufacturer' => 'Dodge','name' => 'Ram 2500'],
            ['manufacturer' => 'Dodge','name' => 'Ram 3500'],
            ['manufacturer' => 'Dodge','name' => 'Ram SRT10'],
            ['manufacturer' => 'Dodge','name' => 'Stratus'],
            ['manufacturer' => 'Dodge','name' => 'Viper'],
            ['manufacturer' => 'Dongfeng','name' => '580'],
            ['manufacturer' => 'Dongfeng','name' => 'A30'],
            ['manufacturer' => 'Dongfeng','name' => 'AX7'],
            ['manufacturer' => 'Dongfeng','name' => 'H30 Cross'],
            ['manufacturer' => 'FAW','name' => 'Besturn B30'],
            ['manufacturer' => 'FAW','name' => 'Besturn B50'],
            ['manufacturer' => 'FAW','name' => 'Besturn X40'],
            ['manufacturer' => 'FAW','name' => 'Besturn X80'],
            ['manufacturer' => 'FAW','name' => 'Oley'],
            ['manufacturer' => 'FAW','name' => 'Vita'],
            ['manufacturer' => 'Ferrari','name' => '348'],
            ['manufacturer' => 'Ferrari','name' => '360'],
            ['manufacturer' => 'Ferrari','name' => '456'],
            ['manufacturer' => 'Ferrari','name' => '458'],
            ['manufacturer' => 'Ferrari','name' => '488'],
            ['manufacturer' => 'Ferrari','name' => '512'],
            ['manufacturer' => 'Ferrari','name' => '550'],
            ['manufacturer' => 'Ferrari','name' => '575 M'],
            ['manufacturer' => 'Ferrari','name' => '599 GTB Fiorano'],
            ['manufacturer' => 'Ferrari','name' => '599 GTO'],
            ['manufacturer' => 'Ferrari','name' => '612'],
            ['manufacturer' => 'Ferrari','name' => '812'],
            ['manufacturer' => 'Ferrari','name' => 'California'],
            ['manufacturer' => 'Ferrari','name' => 'California T'],
            ['manufacturer' => 'Ferrari','name' => 'Challenge Stradale'],
            ['manufacturer' => 'Ferrari','name' => 'Enzo'],
            ['manufacturer' => 'Ferrari','name' => 'F12'],
            ['manufacturer' => 'Ferrari','name' => 'F355'],
            ['manufacturer' => 'Ferrari','name' => 'F430'],
            ['manufacturer' => 'Ferrari','name' => 'F50'],
            ['manufacturer' => 'Ferrari','name' => 'F512 M'],
            ['manufacturer' => 'Ferrari','name' => 'FF'],
            ['manufacturer' => 'Ferrari','name' => 'GTC4 Lusso'],
            ['manufacturer' => 'Ferrari','name' => 'LaFerrari'],
            ['manufacturer' => 'Fiat','name' => '124 Spider'],
            ['manufacturer' => 'Fiat','name' => '500'],
            ['manufacturer' => 'Fiat','name' => '500L'],
            ['manufacturer' => 'Fiat','name' => '500X'],
            ['manufacturer' => 'Fiat','name' => 'Albea'],
            ['manufacturer' => 'Fiat','name' => 'Brava'],
            ['manufacturer' => 'Fiat','name' => 'Bravo'],
            ['manufacturer' => 'Fiat','name' => 'Coupe'],
            ['manufacturer' => 'Fiat','name' => 'Croma'],
            ['manufacturer' => 'Fiat','name' => 'Doblo'],
            ['manufacturer' => 'Fiat','name' => 'Ducato'],
            ['manufacturer' => 'Fiat','name' => 'Freemont'],
            ['manufacturer' => 'Fiat','name' => 'Grande Punto'],
            ['manufacturer' => 'Fiat','name' => 'Idea'],
            ['manufacturer' => 'Fiat','name' => 'Linea'],
            ['manufacturer' => 'Fiat','name' => 'Marea'],
            ['manufacturer' => 'Fiat','name' => 'Multipla'],
            ['manufacturer' => 'Fiat','name' => 'Palio'],
            ['manufacturer' => 'Fiat','name' => 'Panda'],
            ['manufacturer' => 'Fiat','name' => 'Panda 4x4'],
            ['manufacturer' => 'Fiat','name' => 'Punto'],
            ['manufacturer' => 'Fiat','name' => 'Qubo'],
            ['manufacturer' => 'Fiat','name' => 'Sedici'],
            ['manufacturer' => 'Fiat','name' => 'Siena'],
            ['manufacturer' => 'Fiat','name' => 'Stilo'],
            ['manufacturer' => 'Fiat','name' => 'Strada'],
            ['manufacturer' => 'Fiat','name' => 'Tipo'],
            ['manufacturer' => 'Fiat','name' => 'Ulysse'],
            ['manufacturer' => 'Ford','name' => 'B-Max'],
            ['manufacturer' => 'Ford','name' => 'C-Max'],
            ['manufacturer' => 'Ford','name' => 'Cougar'],
            ['manufacturer' => 'Ford','name' => 'Crown Victoria'],
            ['manufacturer' => 'Ford','name' => 'EcoSport'],
            ['manufacturer' => 'Ford','name' => 'Edge'],
            ['manufacturer' => 'Ford','name' => 'Escape'],
            ['manufacturer' => 'Ford','name' => 'Excursion'],
            ['manufacturer' => 'Ford','name' => 'Expedition'],
            ['manufacturer' => 'Ford','name' => 'Explorer'],
            ['manufacturer' => 'Ford','name' => 'Explorer Sport Trac'],
            ['manufacturer' => 'Ford','name' => 'F-150'],
            ['manufacturer' => 'Ford','name' => 'F-250'],
            ['manufacturer' => 'Ford','name' => 'F-350'],
            ['manufacturer' => 'Ford','name' => 'Falcon'],
            ['manufacturer' => 'Ford','name' => 'Fiesta'],
            ['manufacturer' => 'Ford','name' => 'Five Hundred'],
            ['manufacturer' => 'Ford','name' => 'Flex'],
            ['manufacturer' => 'Ford','name' => 'Focus'],
            ['manufacturer' => 'Ford','name' => 'Focus Active'],
            ['manufacturer' => 'Ford','name' => 'Freestar'],
            ['manufacturer' => 'Ford','name' => 'Freestyle'],
            ['manufacturer' => 'Ford','name' => 'Fusion'],
            ['manufacturer' => 'Ford','name' => 'Galaxy'],
            ['manufacturer' => 'Ford','name' => 'Ka'],
            ['manufacturer' => 'Ford','name' => 'Kuga'],
            ['manufacturer' => 'Ford','name' => 'Maverick'],
            ['manufacturer' => 'Ford','name' => 'Mondeo'],
            ['manufacturer' => 'Ford','name' => 'Mustang'],
            ['manufacturer' => 'Ford','name' => 'Mustang Shelby GT350'],
            ['manufacturer' => 'Ford','name' => 'Puma'],
            ['manufacturer' => 'Ford','name' => 'Ranger'],
            ['manufacturer' => 'Ford','name' => 'S-Max'],
            ['manufacturer' => 'Ford','name' => 'Taurus'],
            ['manufacturer' => 'Ford','name' => 'Taurus X'],
            ['manufacturer' => 'Ford','name' => 'Thunderbird'],
            ['manufacturer' => 'Ford','name' => 'Tourneo Connect'],
            ['manufacturer' => 'Ford','name' => 'Transit'],
            ['manufacturer' => 'Ford','name' => 'Transit Connect'],
            ['manufacturer' => 'GAZ','name' => '3102'],
            ['manufacturer' => 'GAZ','name' => '31105'],
            ['manufacturer' => 'GAZ','name' => 'Siber'],
            ['manufacturer' => 'GAZ','name' => 'Sobol'],
            ['manufacturer' => 'Geely','name' => 'Atlas'],
            ['manufacturer' => 'Geely','name' => 'Coolray'],
            ['manufacturer' => 'Geely','name' => 'Emgrand 7'],
            ['manufacturer' => 'Geely','name' => 'Emgrand EC7'],
            ['manufacturer' => 'Geely','name' => 'Emgrand GS'],
            ['manufacturer' => 'Geely','name' => 'Emgrand X7'],
            ['manufacturer' => 'Geely','name' => 'GC9'],
            ['manufacturer' => 'Geely','name' => 'GС6'],
            ['manufacturer' => 'Geely','name' => 'MK'],
            ['manufacturer' => 'Geely','name' => 'Otaka'],
            ['manufacturer' => 'Geely','name' => 'Vision'],
            ['manufacturer' => 'Genesis','name' => 'G70'],
            ['manufacturer' => 'Genesis','name' => 'G80'],
            ['manufacturer' => 'Genesis','name' => 'G90'],
            ['manufacturer' => 'GMC','name' => 'Acadia'],
            ['manufacturer' => 'GMC','name' => 'Canyon'],
            ['manufacturer' => 'GMC','name' => 'Envoy'],
            ['manufacturer' => 'GMC','name' => 'Sierra 1500'],
            ['manufacturer' => 'GMC','name' => 'Sierra 2500'],
            ['manufacturer' => 'GMC','name' => 'Terrain'],
            ['manufacturer' => 'GMC','name' => 'Yukon'],
            ['manufacturer' => 'Great Wall','name' => 'Cowry'],
            ['manufacturer' => 'Great Wall','name' => 'Deer'],
            ['manufacturer' => 'Great Wall','name' => 'Hover'],
            ['manufacturer' => 'Great Wall','name' => 'Hover M2'],
            ['manufacturer' => 'Great Wall','name' => 'Pegasus'],
            ['manufacturer' => 'Great Wall','name' => 'Peri'],
            ['manufacturer' => 'Great Wall','name' => 'Safe'],
            ['manufacturer' => 'Great Wall','name' => 'Sailor'],
            ['manufacturer' => 'Great Wall','name' => 'Sing'],
            ['manufacturer' => 'Great Wall','name' => 'Socool'],
            ['manufacturer' => 'Great Wall','name' => 'Wingle'],
            ['manufacturer' => 'Haval','name' => 'F7'],
            ['manufacturer' => 'Haval','name' => 'H4'],
            ['manufacturer' => 'Haval','name' => 'H6'],
            ['manufacturer' => 'Haval','name' => 'H9'],
            ['manufacturer' => 'Holden','name' => 'Commodore'],
            ['manufacturer' => 'Honda','name' => 'Accord'],
            ['manufacturer' => 'Honda','name' => 'Amaze'],
            ['manufacturer' => 'Honda','name' => 'City'],
            ['manufacturer' => 'Honda','name' => 'Civic'],
            ['manufacturer' => 'Honda','name' => 'CR-V'],
            ['manufacturer' => 'Honda','name' => 'CR-Z'],
            ['manufacturer' => 'Honda','name' => 'Crosstour'],
            ['manufacturer' => 'Honda','name' => 'Element'],
            ['manufacturer' => 'Honda','name' => 'Fit'],
            ['manufacturer' => 'Honda','name' => 'FR-V'],
            ['manufacturer' => 'Honda','name' => 'HR-V'],
            ['manufacturer' => 'Honda','name' => 'HR-V II (GJ)'],
            ['manufacturer' => 'Honda','name' => 'Insight'],
            ['manufacturer' => 'Honda','name' => 'Jade'],
            ['manufacturer' => 'Honda','name' => 'Jazz'],
            ['manufacturer' => 'Honda','name' => 'Legend'],
            ['manufacturer' => 'Honda','name' => 'Odyssey'],
            ['manufacturer' => 'Honda','name' => 'Pilot'],
            ['manufacturer' => 'Honda','name' => 'Prelude'],
            ['manufacturer' => 'Honda','name' => 'Ridgeline'],
            ['manufacturer' => 'Honda','name' => 'S2000'],
            ['manufacturer' => 'Honda','name' => 'Shuttle'],
            ['manufacturer' => 'Honda','name' => 'Stream'],
            ['manufacturer' => 'Honda','name' => 'Vezel'],
            ['manufacturer' => 'Hummer','name' => 'H1'],
            ['manufacturer' => 'Hummer','name' => 'H2'],
            ['manufacturer' => 'Hummer','name' => 'H3'],
            ['manufacturer' => 'Hyundai','name' => 'Accent'],
            ['manufacturer' => 'Hyundai','name' => 'Atos Prime'],
            ['manufacturer' => 'Hyundai','name' => 'Azera'],
            ['manufacturer' => 'Hyundai','name' => 'Centennial'],
            ['manufacturer' => 'Hyundai','name' => 'Creta'],
            ['manufacturer' => 'Hyundai','name' => 'Elantra'],
            ['manufacturer' => 'Hyundai','name' => 'Entourage'],
            ['manufacturer' => 'Hyundai','name' => 'Eon'],
            ['manufacturer' => 'Hyundai','name' => 'Equus'],
            ['manufacturer' => 'Hyundai','name' => 'Galloper'],
            ['manufacturer' => 'Hyundai','name' => 'Genesis'],
            ['manufacturer' => 'Hyundai','name' => 'Genesis Coupe'],
            ['manufacturer' => 'Hyundai','name' => 'Getz'],
            ['manufacturer' => 'Hyundai','name' => 'Grandeur'],
            ['manufacturer' => 'Hyundai','name' => 'H-1'],
            ['manufacturer' => 'Hyundai','name' => 'i10'],
            ['manufacturer' => 'Hyundai','name' => 'i20'],
            ['manufacturer' => 'Hyundai','name' => 'i30'],
            ['manufacturer' => 'Hyundai','name' => 'i30 N'],
            ['manufacturer' => 'Hyundai','name' => 'i40'],
            ['manufacturer' => 'Hyundai','name' => 'Ioniq'],
            ['manufacturer' => 'Hyundai','name' => 'ix20'],
            ['manufacturer' => 'Hyundai','name' => 'ix35'],
            ['manufacturer' => 'Hyundai','name' => 'Kona'],
            ['manufacturer' => 'Hyundai','name' => 'Matrix'],
            ['manufacturer' => 'Hyundai','name' => 'Palisade'],
            ['manufacturer' => 'Hyundai','name' => 'Porter'],
            ['manufacturer' => 'Hyundai','name' => 'Santa Fe'],
            ['manufacturer' => 'Hyundai','name' => 'Solaris'],
            ['manufacturer' => 'Hyundai','name' => 'Sonata'],
            ['manufacturer' => 'Hyundai','name' => 'Terracan'],
            ['manufacturer' => 'Hyundai','name' => 'Trajet'],
            ['manufacturer' => 'Hyundai','name' => 'Tucson'],
            ['manufacturer' => 'Hyundai','name' => 'Veloster'],
            ['manufacturer' => 'Hyundai','name' => 'Veracruz'],
            ['manufacturer' => 'Hyundai','name' => 'Verna'],
            ['manufacturer' => 'Hyundai','name' => 'Xcent'],
            ['manufacturer' => 'Hyundai','name' => 'XG'],
            ['manufacturer' => 'Infiniti','name' => 'EX'],
            ['manufacturer' => 'Infiniti','name' => 'FX'],
            ['manufacturer' => 'Infiniti','name' => 'G'],
            ['manufacturer' => 'Infiniti','name' => 'I35'],
            ['manufacturer' => 'Infiniti','name' => 'JX'],
            ['manufacturer' => 'Infiniti','name' => 'M'],
            ['manufacturer' => 'Infiniti','name' => 'Q30'],
            ['manufacturer' => 'Infiniti','name' => 'Q40'],
            ['manufacturer' => 'Infiniti','name' => 'Q45'],
            ['manufacturer' => 'Infiniti','name' => 'Q50'],
            ['manufacturer' => 'Infiniti','name' => 'Q60'],
            ['manufacturer' => 'Infiniti','name' => 'Q70'],
            ['manufacturer' => 'Infiniti','name' => 'QX30'],
            ['manufacturer' => 'Infiniti','name' => 'QX4'],
            ['manufacturer' => 'Infiniti','name' => 'QX50'],
            ['manufacturer' => 'Infiniti','name' => 'QX56'],
            ['manufacturer' => 'Infiniti','name' => 'QX60'],
            ['manufacturer' => 'Infiniti','name' => 'QX70'],
            ['manufacturer' => 'Infiniti','name' => 'QX80'],
            ['manufacturer' => 'Isuzu','name' => 'Ascender'],
            ['manufacturer' => 'Isuzu','name' => 'Axiom'],
            ['manufacturer' => 'Isuzu','name' => 'D-Max'],
            ['manufacturer' => 'Isuzu','name' => 'D-Max Rodeo'],
            ['manufacturer' => 'Isuzu','name' => 'I280'],
            ['manufacturer' => 'Isuzu','name' => 'I290'],
            ['manufacturer' => 'Isuzu','name' => 'I350'],
            ['manufacturer' => 'Isuzu','name' => 'I370'],
            ['manufacturer' => 'Isuzu','name' => 'Rodeo'],
            ['manufacturer' => 'Isuzu','name' => 'Trooper'],
            ['manufacturer' => 'Isuzu','name' => 'VehiCross'],
            ['manufacturer' => 'Iveco','name' => 'Daily'],
            ['manufacturer' => 'Jaguar','name' => 'E-Pace'],
            ['manufacturer' => 'Jaguar','name' => 'F-Pace'],
            ['manufacturer' => 'Jaguar','name' => 'F-Type'],
            ['manufacturer' => 'Jaguar','name' => 'I-Pace'],
            ['manufacturer' => 'Jaguar','name' => 'S-Type'],
            ['manufacturer' => 'Jaguar','name' => 'X-Type'],
            ['manufacturer' => 'Jaguar','name' => 'XE'],
            ['manufacturer' => 'Jaguar','name' => 'XF'],
            ['manufacturer' => 'Jaguar','name' => 'XJ'],
            ['manufacturer' => 'Jaguar','name' => 'XK/XKR'],
            ['manufacturer' => 'Jeep','name' => 'Cherokee'],
            ['manufacturer' => 'Jeep','name' => 'Commander'],
            ['manufacturer' => 'Jeep','name' => 'Compass'],
            ['manufacturer' => 'Jeep','name' => 'Gladiator'],
            ['manufacturer' => 'Jeep','name' => 'Grand Cherokee'],
            ['manufacturer' => 'Jeep','name' => 'Liberty'],
            ['manufacturer' => 'Jeep','name' => 'Patriot'],
            ['manufacturer' => 'Jeep','name' => 'Renegade'],
            ['manufacturer' => 'Jeep','name' => 'Wrangler'],
            ['manufacturer' => 'Kia','name' => 'Carens'],
            ['manufacturer' => 'Kia','name' => 'Carnival'],
            ['manufacturer' => 'Kia','name' => 'Ceed'],
            ['manufacturer' => 'Kia','name' => 'Cerato'],
            ['manufacturer' => 'Kia','name' => 'Clarus'],
            ['manufacturer' => 'Kia','name' => 'Forte'],
            ['manufacturer' => 'Kia','name' => 'K900'],
            ['manufacturer' => 'Kia','name' => 'Magentis'],
            ['manufacturer' => 'Kia','name' => 'Mohave'],
            ['manufacturer' => 'Kia','name' => 'Niro'],
            ['manufacturer' => 'Kia','name' => 'Opirus'],
            ['manufacturer' => 'Kia','name' => 'Optima'],
            ['manufacturer' => 'Kia','name' => 'Picanto'],
            ['manufacturer' => 'Kia','name' => 'ProCeed'],
            ['manufacturer' => 'Kia','name' => 'Quoris'],
            ['manufacturer' => 'Kia','name' => 'Ray'],
            ['manufacturer' => 'Kia','name' => 'Rio'],
            ['manufacturer' => 'Kia','name' => 'Rio X-Line'],
            ['manufacturer' => 'Kia','name' => 'Seltos'],
            ['manufacturer' => 'Kia','name' => 'Shuma'],
            ['manufacturer' => 'Kia','name' => 'Sorento'],
            ['manufacturer' => 'Kia','name' => 'Sorento Prime'],
            ['manufacturer' => 'Kia','name' => 'Soul'],
            ['manufacturer' => 'Kia','name' => 'Spectra'],
            ['manufacturer' => 'Kia','name' => 'Sportage'],
            ['manufacturer' => 'Kia','name' => 'Stinger'],
            ['manufacturer' => 'Kia','name' => 'Stonic'],
            ['manufacturer' => 'Kia','name' => 'Telluride'],
            ['manufacturer' => 'Kia','name' => 'Venga'],
            ['manufacturer' => 'Lamborghini','name' => 'Aventador'],
            ['manufacturer' => 'Lamborghini','name' => 'Centenario'],
            ['manufacturer' => 'Lamborghini','name' => 'Diablo'],
            ['manufacturer' => 'Lamborghini','name' => 'Gallardo'],
            ['manufacturer' => 'Lamborghini','name' => 'Huracan'],
            ['manufacturer' => 'Lamborghini','name' => 'Murcielago'],
            ['manufacturer' => 'Lamborghini','name' => 'Reventon'],
            ['manufacturer' => 'Lamborghini','name' => 'Urus'],
            ['manufacturer' => 'Lancia','name' => 'Delta'],
            ['manufacturer' => 'Lancia','name' => 'Lybra'],
            ['manufacturer' => 'Lancia','name' => 'Musa'],
            ['manufacturer' => 'Lancia','name' => 'Phedra'],
            ['manufacturer' => 'Lancia','name' => 'Thema'],
            ['manufacturer' => 'Lancia','name' => 'Thesis'],
            ['manufacturer' => 'Lancia','name' => 'Ypsilon'],
            ['manufacturer' => 'Land Rover','name' => 'Defender'],
            ['manufacturer' => 'Land Rover','name' => 'Discovery'],
            ['manufacturer' => 'Land Rover','name' => 'Discovery Sport'],
            ['manufacturer' => 'Land Rover','name' => 'Evoque'],
            ['manufacturer' => 'Land Rover','name' => 'Freelander'],
            ['manufacturer' => 'Land Rover','name' => 'Range Rover'],
            ['manufacturer' => 'Land Rover','name' => 'Range Rover Sport'],
            ['manufacturer' => 'Land Rover','name' => 'Range Rover Velar'],
            ['manufacturer' => 'Lexus','name' => 'CT'],
            ['manufacturer' => 'Lexus','name' => 'ES'],
            ['manufacturer' => 'Lexus','name' => 'GS'],
            ['manufacturer' => 'Lexus','name' => 'GX'],
            ['manufacturer' => 'Lexus','name' => 'HS'],
            ['manufacturer' => 'Lexus','name' => 'IS'],
            ['manufacturer' => 'Lexus','name' => 'LC'],
            ['manufacturer' => 'Lexus','name' => 'LFA'],
            ['manufacturer' => 'Lexus','name' => 'LS'],
            ['manufacturer' => 'Lexus','name' => 'LX'],
            ['manufacturer' => 'Lexus','name' => 'NX'],
            ['manufacturer' => 'Lexus','name' => 'RC'],
            ['manufacturer' => 'Lexus','name' => 'RX'],
            ['manufacturer' => 'Lexus','name' => 'SC'],
            ['manufacturer' => 'Lexus','name' => 'UX'],
            ['manufacturer' => 'Lifan','name' => 'Breez'],
            ['manufacturer' => 'Lifan','name' => 'Cebrium'],
            ['manufacturer' => 'Lifan','name' => 'Celliya'],
            ['manufacturer' => 'Lifan','name' => 'Smily'],
            ['manufacturer' => 'Lifan','name' => 'Solano'],
            ['manufacturer' => 'Lifan','name' => 'X50'],
            ['manufacturer' => 'Lifan','name' => 'X60'],
            ['manufacturer' => 'Lincoln','name' => 'Aviator'],
            ['manufacturer' => 'Lincoln','name' => 'Corsair'],
            ['manufacturer' => 'Lincoln','name' => 'Mark LT'],
            ['manufacturer' => 'Lincoln','name' => 'MKC'],
            ['manufacturer' => 'Lincoln','name' => 'MKS'],
            ['manufacturer' => 'Lincoln','name' => 'MKT'],
            ['manufacturer' => 'Lincoln','name' => 'MKX'],
            ['manufacturer' => 'Lincoln','name' => 'MKZ'],
            ['manufacturer' => 'Lincoln','name' => 'Navigator'],
            ['manufacturer' => 'Lincoln','name' => 'Town Car'],
            ['manufacturer' => 'Lincoln','name' => 'Zephyr'],
            ['manufacturer' => 'Lotus','name' => 'Elise'],
            ['manufacturer' => 'Lotus','name' => 'Europa S'],
            ['manufacturer' => 'Lotus','name' => 'Evora'],
            ['manufacturer' => 'Lotus','name' => 'Exige'],
            ['manufacturer' => 'Marussia','name' => 'B1'],
            ['manufacturer' => 'Marussia','name' => 'B2'],
            ['manufacturer' => 'Maserati','name' => '3200 GT'],
            ['manufacturer' => 'Maserati','name' => 'Ghibli'],
            ['manufacturer' => 'Maserati','name' => 'Gran Cabrio'],
            ['manufacturer' => 'Maserati','name' => 'Gran Turismo '],
            ['manufacturer' => 'Maserati','name' => 'Gran Turismo S'],
            ['manufacturer' => 'Maserati','name' => 'Levante'],
            ['manufacturer' => 'Maserati','name' => 'Quattroporte'],
            ['manufacturer' => 'Maserati','name' => 'Quattroporte S'],
            ['manufacturer' => 'Maybach','name' => '57'],
            ['manufacturer' => 'Maybach','name' => '57 S'],
            ['manufacturer' => 'Maybach','name' => '62'],
            ['manufacturer' => 'Maybach','name' => '62 S'],
            ['manufacturer' => 'Maybach','name' => 'Landaulet'],
            ['manufacturer' => 'Mazda','name' => '2'],
            ['manufacturer' => 'Mazda','name' => '3'],
            ['manufacturer' => 'Mazda','name' => '323'],
            ['manufacturer' => 'Mazda','name' => '5'],
            ['manufacturer' => 'Mazda','name' => '6'],
            ['manufacturer' => 'Mazda','name' => '626'],
            ['manufacturer' => 'Mazda','name' => 'B-Series'],
            ['manufacturer' => 'Mazda','name' => 'BT-50'],
            ['manufacturer' => 'Mazda','name' => 'CX-3'],
            ['manufacturer' => 'Mazda','name' => 'CX-5'],
            ['manufacturer' => 'Mazda','name' => 'CX-7'],
            ['manufacturer' => 'Mazda','name' => 'CX-9'],
            ['manufacturer' => 'Mazda','name' => 'MPV'],
            ['manufacturer' => 'Mazda','name' => 'MX-5'],
            ['manufacturer' => 'Mazda','name' => 'Premacy'],
            ['manufacturer' => 'Mazda','name' => 'RX-7'],
            ['manufacturer' => 'Mazda','name' => 'RX-8'],
            ['manufacturer' => 'Mazda','name' => 'Tribute'],
            ['manufacturer' => 'McLaren','name' => '540C'],
            ['manufacturer' => 'McLaren','name' => '570S'],
            ['manufacturer' => 'McLaren','name' => '600LT'],
            ['manufacturer' => 'McLaren','name' => '650S'],
            ['manufacturer' => 'McLaren','name' => '675LT'],
            ['manufacturer' => 'McLaren','name' => '720S'],
            ['manufacturer' => 'McLaren','name' => 'MP4-12C'],
            ['manufacturer' => 'McLaren','name' => 'P1'],
            ['manufacturer' => 'Mercedes','name' => 'A-class'],
            ['manufacturer' => 'Mercedes','name' => 'AMG GT'],
            ['manufacturer' => 'Mercedes','name' => 'AMG GT 4-Door'],
            ['manufacturer' => 'Mercedes','name' => 'B-class'],
            ['manufacturer' => 'Mercedes','name' => 'C-class'],
            ['manufacturer' => 'Mercedes','name' => 'C-class Sport Coupe'],
            ['manufacturer' => 'Mercedes','name' => 'CL-class'],
            ['manufacturer' => 'Mercedes','name' => 'CLA-class'],
            ['manufacturer' => 'Mercedes','name' => 'CLC-class '],
            ['manufacturer' => 'Mercedes','name' => 'CLK-class'],
            ['manufacturer' => 'Mercedes','name' => 'CLS-class'],
            ['manufacturer' => 'Mercedes','name' => 'E-class'],
            ['manufacturer' => 'Mercedes','name' => 'E-class Coupe'],
            ['manufacturer' => 'Mercedes','name' => 'EQC'],
            ['manufacturer' => 'Mercedes','name' => 'G-class'],
            ['manufacturer' => 'Mercedes','name' => 'GL-class'],
            ['manufacturer' => 'Mercedes','name' => 'GLA-class'],
            ['manufacturer' => 'Mercedes','name' => 'GLC-class'],
            ['manufacturer' => 'Mercedes','name' => 'GLC-class Coupe'],
            ['manufacturer' => 'Mercedes','name' => 'GLE-class'],
            ['manufacturer' => 'Mercedes','name' => 'GLE-class Coupe'],
            ['manufacturer' => 'Mercedes','name' => 'GLK-class'],
            ['manufacturer' => 'Mercedes','name' => 'GLS-class'],
            ['manufacturer' => 'Mercedes','name' => 'M-class'],
            ['manufacturer' => 'Mercedes','name' => 'R-class'],
            ['manufacturer' => 'Mercedes','name' => 'S-class'],
            ['manufacturer' => 'Mercedes','name' => 'S-class Cabrio'],
            ['manufacturer' => 'Mercedes','name' => 'S-class Coupe'],
            ['manufacturer' => 'Mercedes','name' => 'SL-class'],
            ['manufacturer' => 'Mercedes','name' => 'SLK-class'],
            ['manufacturer' => 'Mercedes','name' => 'SLR-class'],
            ['manufacturer' => 'Mercedes','name' => 'SLS AMG'],
            ['manufacturer' => 'Mercedes','name' => 'Sprinter'],
            ['manufacturer' => 'Mercedes','name' => 'Vaneo'],
            ['manufacturer' => 'Mercedes','name' => 'Viano'],
            ['manufacturer' => 'Mercedes','name' => 'Vito'],
            ['manufacturer' => 'Mercedes','name' => 'X-class'],
            ['manufacturer' => 'Mercury','name' => 'Grand Marquis'],
            ['manufacturer' => 'Mercury','name' => 'Mariner'],
            ['manufacturer' => 'Mercury','name' => 'Milan'],
            ['manufacturer' => 'Mercury','name' => 'Montego'],
            ['manufacturer' => 'Mercury','name' => 'Monterey'],
            ['manufacturer' => 'Mercury','name' => 'Mountaineer'],
            ['manufacturer' => 'Mercury','name' => 'Sable'],
            ['manufacturer' => 'MG','name' => 'TF'],
            ['manufacturer' => 'MG','name' => 'XPower SV'],
            ['manufacturer' => 'MG','name' => 'ZR'],
            ['manufacturer' => 'MG','name' => 'ZS'],
            ['manufacturer' => 'MG','name' => 'ZT'],
            ['manufacturer' => 'MG','name' => 'ZT-T'],
            ['manufacturer' => 'Mini','name' => 'Clubman'],
            ['manufacturer' => 'Mini','name' => 'Clubman S'],
            ['manufacturer' => 'Mini','name' => 'Clubvan'],
            ['manufacturer' => 'Mini','name' => 'Cooper'],
            ['manufacturer' => 'Mini','name' => 'Cooper Cabrio'],
            ['manufacturer' => 'Mini','name' => 'Cooper S'],
            ['manufacturer' => 'Mini','name' => 'Cooper S Cabrio'],
            ['manufacturer' => 'Mini','name' => 'Cooper S Countryman All4'],
            ['manufacturer' => 'Mini','name' => 'Countryman'],
            ['manufacturer' => 'Mini','name' => 'One'],
            ['manufacturer' => 'Mitsubishi','name' => '3000 GT'],
            ['manufacturer' => 'Mitsubishi','name' => 'ASX'],
            ['manufacturer' => 'Mitsubishi','name' => 'Carisma'],
            ['manufacturer' => 'Mitsubishi','name' => 'Colt'],
            ['manufacturer' => 'Mitsubishi','name' => 'Dignity'],
            ['manufacturer' => 'Mitsubishi','name' => 'Eclipse'],
            ['manufacturer' => 'Mitsubishi','name' => 'Eclipse Cross'],
            ['manufacturer' => 'Mitsubishi','name' => 'Endeavor'],
            ['manufacturer' => 'Mitsubishi','name' => 'Galant'],
            ['manufacturer' => 'Mitsubishi','name' => 'Grandis'],
            ['manufacturer' => 'Mitsubishi','name' => 'i-MiEV'],
            ['manufacturer' => 'Mitsubishi','name' => 'L200'],
            ['manufacturer' => 'Mitsubishi','name' => 'Lancer'],
            ['manufacturer' => 'Mitsubishi','name' => 'Lancer Evo'],
            ['manufacturer' => 'Mitsubishi','name' => 'Mirage'],
            ['manufacturer' => 'Mitsubishi','name' => 'Outlander'],
            ['manufacturer' => 'Mitsubishi','name' => 'Outlander XL'],
            ['manufacturer' => 'Mitsubishi','name' => 'Pajero'],
            ['manufacturer' => 'Mitsubishi','name' => 'Pajero Pinin'],
            ['manufacturer' => 'Mitsubishi','name' => 'Pajero Sport'],
            ['manufacturer' => 'Mitsubishi','name' => 'Raider'],
            ['manufacturer' => 'Mitsubishi','name' => 'Space Gear'],
            ['manufacturer' => 'Mitsubishi','name' => 'Space Runner'],
            ['manufacturer' => 'Mitsubishi','name' => 'Space Star'],
            ['manufacturer' => 'Nissan','name' => '350Z'],
            ['manufacturer' => 'Nissan','name' => '370Z'],
            ['manufacturer' => 'Nissan','name' => 'Almera'],
            ['manufacturer' => 'Nissan','name' => 'Almera Classic'],
            ['manufacturer' => 'Nissan','name' => 'Almera Tino'],
            ['manufacturer' => 'Nissan','name' => 'Altima'],
            ['manufacturer' => 'Nissan','name' => 'Armada'],
            ['manufacturer' => 'Nissan','name' => 'Bluebird Sylphy'],
            ['manufacturer' => 'Nissan','name' => 'GT-R'],
            ['manufacturer' => 'Nissan','name' => 'Juke'],
            ['manufacturer' => 'Nissan','name' => 'Leaf'],
            ['manufacturer' => 'Nissan','name' => 'Maxima'],
            ['manufacturer' => 'Nissan','name' => 'Micra'],
            ['manufacturer' => 'Nissan','name' => 'Murano'],
            ['manufacturer' => 'Nissan','name' => 'Navara'],
            ['manufacturer' => 'Nissan','name' => 'Note'],
            ['manufacturer' => 'Nissan','name' => 'NP300'],
            ['manufacturer' => 'Nissan','name' => 'Pathfinder'],
            ['manufacturer' => 'Nissan','name' => 'Patrol'],
            ['manufacturer' => 'Nissan','name' => 'Primera'],
            ['manufacturer' => 'Nissan','name' => 'Qashqai'],
            ['manufacturer' => 'Nissan','name' => 'Qashqai+2'],
            ['manufacturer' => 'Nissan','name' => 'Quest'],
            ['manufacturer' => 'Nissan','name' => 'Rogue'],
            ['manufacturer' => 'Nissan','name' => 'Sentra'],
            ['manufacturer' => 'Nissan','name' => 'Skyline'],
            ['manufacturer' => 'Nissan','name' => 'Sylphy'],
            ['manufacturer' => 'Nissan','name' => 'Teana'],
            ['manufacturer' => 'Nissan','name' => 'Terrano'],
            ['manufacturer' => 'Nissan','name' => 'Tiida'],
            ['manufacturer' => 'Nissan','name' => 'Titan'],
            ['manufacturer' => 'Nissan','name' => 'Titan XD'],
            ['manufacturer' => 'Nissan','name' => 'X-Trail'],
            ['manufacturer' => 'Nissan','name' => 'XTerra'],
            ['manufacturer' => 'Nissan','name' => 'Z'],
            ['manufacturer' => 'Opel','name' => 'Adam'],
            ['manufacturer' => 'Opel','name' => 'Agila'],
            ['manufacturer' => 'Opel','name' => 'Antara'],
            ['manufacturer' => 'Opel','name' => 'Astra'],
            ['manufacturer' => 'Opel','name' => 'Astra GTS'],
            ['manufacturer' => 'Opel','name' => 'Cascada'],
            ['manufacturer' => 'Opel','name' => 'Combo'],
            ['manufacturer' => 'Opel','name' => 'Corsa'],
            ['manufacturer' => 'Opel','name' => 'Corsa OPC'],
            ['manufacturer' => 'Opel','name' => 'Crossland X'],
            ['manufacturer' => 'Opel','name' => 'Frontera'],
            ['manufacturer' => 'Opel','name' => 'Grandland X'],
            ['manufacturer' => 'Opel','name' => 'Insignia'],
            ['manufacturer' => 'Opel','name' => 'Insignia OPC'],
            ['manufacturer' => 'Opel','name' => 'Karl'],
            ['manufacturer' => 'Opel','name' => 'Meriva'],
            ['manufacturer' => 'Opel','name' => 'Mokka'],
            ['manufacturer' => 'Opel','name' => 'Omega'],
            ['manufacturer' => 'Opel','name' => 'Signum'],
            ['manufacturer' => 'Opel','name' => 'Speedster'],
            ['manufacturer' => 'Opel','name' => 'Tigra'],
            ['manufacturer' => 'Opel','name' => 'Vectra'],
            ['manufacturer' => 'Opel','name' => 'Vivaro'],
            ['manufacturer' => 'Opel','name' => 'Zafira'],
            ['manufacturer' => 'Opel','name' => 'Zafira Tourer'],
            ['manufacturer' => 'Peugeot','name' => '1007'],
            ['manufacturer' => 'Peugeot','name' => '107'],
            ['manufacturer' => 'Peugeot','name' => '108'],
            ['manufacturer' => 'Peugeot','name' => '2008'],
            ['manufacturer' => 'Peugeot','name' => '206'],
            ['manufacturer' => 'Peugeot','name' => '207'],
            ['manufacturer' => 'Peugeot','name' => '208'],
            ['manufacturer' => 'Peugeot','name' => '3008'],
            ['manufacturer' => 'Peugeot','name' => '301'],
            ['manufacturer' => 'Peugeot','name' => '307'],
            ['manufacturer' => 'Peugeot','name' => '308'],
            ['manufacturer' => 'Peugeot','name' => '4007'],
            ['manufacturer' => 'Peugeot','name' => '4008'],
            ['manufacturer' => 'Peugeot','name' => '406'],
            ['manufacturer' => 'Peugeot','name' => '407'],
            ['manufacturer' => 'Peugeot','name' => '408'],
            ['manufacturer' => 'Peugeot','name' => '5008'],
            ['manufacturer' => 'Peugeot','name' => '508'],
            ['manufacturer' => 'Peugeot','name' => '607'],
            ['manufacturer' => 'Peugeot','name' => '807'],
            ['manufacturer' => 'Peugeot','name' => 'Boxer'],
            ['manufacturer' => 'Peugeot','name' => 'Partner'],
            ['manufacturer' => 'Peugeot','name' => 'RCZ Sport'],
            ['manufacturer' => 'Plymouth','name' => 'Road Runner'],
            ['manufacturer' => 'Pontiac','name' => 'Aztec'],
            ['manufacturer' => 'Pontiac','name' => 'Bonneville'],
            ['manufacturer' => 'Pontiac','name' => 'Firebird'],
            ['manufacturer' => 'Pontiac','name' => 'G5 Pursuit'],
            ['manufacturer' => 'Pontiac','name' => 'G6'],
            ['manufacturer' => 'Pontiac','name' => 'G8'],
            ['manufacturer' => 'Pontiac','name' => 'Grand AM'],
            ['manufacturer' => 'Pontiac','name' => 'Grand Prix'],
            ['manufacturer' => 'Pontiac','name' => 'GTO'],
            ['manufacturer' => 'Pontiac','name' => 'Montana'],
            ['manufacturer' => 'Pontiac','name' => 'Solstice'],
            ['manufacturer' => 'Pontiac','name' => 'Sunfire'],
            ['manufacturer' => 'Pontiac','name' => 'Torrent'],
            ['manufacturer' => 'Pontiac','name' => 'Vibe'],
            ['manufacturer' => 'Porsche','name' => '718 Boxster'],
            ['manufacturer' => 'Porsche','name' => '718 Cayman'],
            ['manufacturer' => 'Porsche','name' => '911'],
            ['manufacturer' => 'Porsche','name' => 'Boxster'],
            ['manufacturer' => 'Porsche','name' => 'Cayenne'],
            ['manufacturer' => 'Porsche','name' => 'Cayman'],
            ['manufacturer' => 'Porsche','name' => 'Macan'],
            ['manufacturer' => 'Porsche','name' => 'Panamera'],
            ['manufacturer' => 'Porsche','name' => 'Taycan'],
            ['manufacturer' => 'Ravon','name' => 'Gentra'],
            ['manufacturer' => 'Renault','name' => 'Arkana'],
            ['manufacturer' => 'Renault','name' => 'Avantime'],
            ['manufacturer' => 'Renault','name' => 'Captur'],
            ['manufacturer' => 'Renault','name' => 'Clio'],
            ['manufacturer' => 'Renault','name' => 'Duster'],
            ['manufacturer' => 'Renault','name' => 'Duster Oroch'],
            ['manufacturer' => 'Renault','name' => 'Espace'],
            ['manufacturer' => 'Renault','name' => 'Fluence'],
            ['manufacturer' => 'Renault','name' => 'Grand Scenic'],
            ['manufacturer' => 'Renault','name' => 'Kadjar'],
            ['manufacturer' => 'Renault','name' => 'Kangoo'],
            ['manufacturer' => 'Renault','name' => 'Kaptur'],
            ['manufacturer' => 'Renault','name' => 'Koleos'],
            ['manufacturer' => 'Renault','name' => 'Laguna'],
            ['manufacturer' => 'Renault','name' => 'Latitude'],
            ['manufacturer' => 'Renault','name' => 'Logan'],
            ['manufacturer' => 'Renault','name' => 'Master'],
            ['manufacturer' => 'Renault','name' => 'Megane'],
            ['manufacturer' => 'Renault','name' => 'Modus'],
            ['manufacturer' => 'Renault','name' => 'Sandero'],
            ['manufacturer' => 'Renault','name' => 'Sandero Stepway'],
            ['manufacturer' => 'Renault','name' => 'Scenic'],
            ['manufacturer' => 'Renault','name' => 'Symbol'],
            ['manufacturer' => 'Renault','name' => 'Talisman'],
            ['manufacturer' => 'Renault','name' => 'Trafic'],
            ['manufacturer' => 'Renault','name' => 'Twingo'],
            ['manufacturer' => 'Renault','name' => 'Twizy'],
            ['manufacturer' => 'Renault','name' => 'Vel Satis'],
            ['manufacturer' => 'Renault','name' => 'Wind'],
            ['manufacturer' => 'Renault','name' => 'Zoe'],
            ['manufacturer' => 'Rolls-Royce','name' => 'Cullinan'],
            ['manufacturer' => 'Rolls-Royce','name' => 'Dawn'],
            ['manufacturer' => 'Rolls-Royce','name' => 'Ghost'],
            ['manufacturer' => 'Rolls-Royce','name' => 'Phantom'],
            ['manufacturer' => 'Rolls-Royce','name' => 'Wraith'],
            ['manufacturer' => 'Rover','name' => '25'],
            ['manufacturer' => 'Rover','name' => '400'],
            ['manufacturer' => 'Rover','name' => '45'],
            ['manufacturer' => 'Rover','name' => '600'],
            ['manufacturer' => 'Rover','name' => '75'],
            ['manufacturer' => 'Rover','name' => 'Streetwise'],
            ['manufacturer' => 'Saab','name' => '9-2x'],
            ['manufacturer' => 'Saab','name' => '09.���'],
            ['manufacturer' => 'Saab','name' => '9-4x'],
            ['manufacturer' => 'Saab','name' => '09.���'],
            ['manufacturer' => 'Saab','name' => '9-7x'],
            ['manufacturer' => 'Saturn','name' => 'Aura'],
            ['manufacturer' => 'Saturn','name' => 'Ion'],
            ['manufacturer' => 'Saturn','name' => 'LW'],
            ['manufacturer' => 'Saturn','name' => 'Outlook'],
            ['manufacturer' => 'Saturn','name' => 'Sky'],
            ['manufacturer' => 'Saturn','name' => 'Vue'],
            ['manufacturer' => 'Scion','name' => 'FR-S'],
            ['manufacturer' => 'Scion','name' => 'tC'],
            ['manufacturer' => 'Scion','name' => 'xA'],
            ['manufacturer' => 'Scion','name' => 'xB'],
            ['manufacturer' => 'Scion','name' => 'xD'],
            ['manufacturer' => 'Seat','name' => 'Alhambra'],
            ['manufacturer' => 'Seat','name' => 'Altea'],
            ['manufacturer' => 'Seat','name' => 'Altea Freetrack'],
            ['manufacturer' => 'Seat','name' => 'Altea XL'],
            ['manufacturer' => 'Seat','name' => 'Arosa'],
            ['manufacturer' => 'Seat','name' => 'Ateca'],
            ['manufacturer' => 'Seat','name' => 'Cordoba'],
            ['manufacturer' => 'Seat','name' => 'Exeo'],
            ['manufacturer' => 'Seat','name' => 'Ibiza'],
            ['manufacturer' => 'Seat','name' => 'Leon'],
            ['manufacturer' => 'Seat','name' => 'Mii'],
            ['manufacturer' => 'Seat','name' => 'Toledo'],
            ['manufacturer' => 'Skoda','name' => 'Citigo'],
            ['manufacturer' => 'Skoda','name' => 'Fabia'],
            ['manufacturer' => 'Skoda','name' => 'Felicia'],
            ['manufacturer' => 'Skoda','name' => 'Kamiq'],
            ['manufacturer' => 'Skoda','name' => 'Karoq'],
            ['manufacturer' => 'Skoda','name' => 'Kodiaq'],
            ['manufacturer' => 'Skoda','name' => 'Octavia'],
            ['manufacturer' => 'Skoda','name' => 'Octavia Scout'],
            ['manufacturer' => 'Skoda','name' => 'Octavia Tour'],
            ['manufacturer' => 'Skoda','name' => 'Praktik'],
            ['manufacturer' => 'Skoda','name' => 'Rapid'],
            ['manufacturer' => 'Skoda','name' => 'Rapid Spaceback (NH1)'],
            ['manufacturer' => 'Skoda','name' => 'Roomster'],
            ['manufacturer' => 'Skoda','name' => 'Superb'],
            ['manufacturer' => 'Skoda','name' => 'Yeti'],
            ['manufacturer' => 'Smart','name' => 'Forfour'],
            ['manufacturer' => 'Smart','name' => 'Fortwo'],
            ['manufacturer' => 'Smart','name' => 'Roadster'],
            ['manufacturer' => 'Ssang Yong','name' => 'Actyon'],
            ['manufacturer' => 'Ssang Yong','name' => 'Actyon Sports'],
            ['manufacturer' => 'Ssang Yong','name' => 'Chairman'],
            ['manufacturer' => 'Ssang Yong','name' => 'Korando'],
            ['manufacturer' => 'Ssang Yong','name' => 'Kyron'],
            ['manufacturer' => 'Ssang Yong','name' => 'Musso'],
            ['manufacturer' => 'Ssang Yong','name' => 'Musso Sport'],
            ['manufacturer' => 'Ssang Yong','name' => 'Rexton'],
            ['manufacturer' => 'Ssang Yong','name' => 'Rodius'],
            ['manufacturer' => 'Ssang Yong','name' => 'Stavic'],
            ['manufacturer' => 'Ssang Yong','name' => 'Tivoli'],
            ['manufacturer' => 'Subaru','name' => 'Ascent'],
            ['manufacturer' => 'Subaru','name' => 'Baja'],
            ['manufacturer' => 'Subaru','name' => 'Exiga'],
            ['manufacturer' => 'Subaru','name' => 'Forester'],
            ['manufacturer' => 'Subaru','name' => 'Impreza'],
            ['manufacturer' => 'Subaru','name' => 'Justy'],
            ['manufacturer' => 'Subaru','name' => 'Legacy'],
            ['manufacturer' => 'Subaru','name' => 'Levorg'],
            ['manufacturer' => 'Subaru','name' => 'Outback'],
            ['manufacturer' => 'Subaru','name' => 'Traviq'],
            ['manufacturer' => 'Subaru','name' => 'Tribeca'],
            ['manufacturer' => 'Subaru','name' => 'WRX'],
            ['manufacturer' => 'Subaru','name' => 'XV'],
            ['manufacturer' => 'Suzuki','name' => 'Alto'],
            ['manufacturer' => 'Suzuki','name' => 'Baleno'],
            ['manufacturer' => 'Suzuki','name' => 'Celerio'],
            ['manufacturer' => 'Suzuki','name' => 'Ciaz'],
            ['manufacturer' => 'Suzuki','name' => 'Grand Vitara'],
            ['manufacturer' => 'Suzuki','name' => 'Grand Vitara XL7'],
            ['manufacturer' => 'Suzuki','name' => 'Ignis'],
            ['manufacturer' => 'Suzuki','name' => 'Jimny'],
            ['manufacturer' => 'Suzuki','name' => 'Kizashi'],
            ['manufacturer' => 'Suzuki','name' => 'Liana'],
            ['manufacturer' => 'Suzuki','name' => 'Splash'],
            ['manufacturer' => 'Suzuki','name' => 'Swift'],
            ['manufacturer' => 'Suzuki','name' => 'SX4'],
            ['manufacturer' => 'Suzuki','name' => 'Vitara'],
            ['manufacturer' => 'Suzuki','name' => 'Wagon R'],
            ['manufacturer' => 'Suzuki','name' => 'Wagon R+'],
            ['manufacturer' => 'Tesla','name' => 'Model 3'],
            ['manufacturer' => 'Tesla','name' => 'Model S'],
            ['manufacturer' => 'Tesla','name' => 'Model X'],
            ['manufacturer' => 'Tesla','name' => 'Model Y'],
            ['manufacturer' => 'Toyota','name' => '4Runner'],
            ['manufacturer' => 'Toyota','name' => 'Alphard'],
            ['manufacturer' => 'Toyota','name' => 'Auris'],
            ['manufacturer' => 'Toyota','name' => 'Avalon'],
            ['manufacturer' => 'Toyota','name' => 'Avensis'],
            ['manufacturer' => 'Toyota','name' => 'Avensis Verso'],
            ['manufacturer' => 'Toyota','name' => 'Aygo'],
            ['manufacturer' => 'Toyota','name' => 'C-HR'],
            ['manufacturer' => 'Toyota','name' => 'Caldina'],
            ['manufacturer' => 'Toyota','name' => 'Camry'],
            ['manufacturer' => 'Toyota','name' => 'Celica'],
            ['manufacturer' => 'Toyota','name' => 'Corolla'],
            ['manufacturer' => 'Toyota','name' => 'Corolla Verso'],
            ['manufacturer' => 'Toyota','name' => 'FJ Cruiser'],
            ['manufacturer' => 'Toyota','name' => 'Fortuner'],
            ['manufacturer' => 'Toyota','name' => 'GT 86'],
            ['manufacturer' => 'Toyota','name' => 'Hiace'],
            ['manufacturer' => 'Toyota','name' => 'Highlander'],
            ['manufacturer' => 'Toyota','name' => 'Hilux'],
            ['manufacturer' => 'Toyota','name' => 'iQ'],
            ['manufacturer' => 'Toyota','name' => 'ist'],
            ['manufacturer' => 'Toyota','name' => 'Land Cruiser'],
            ['manufacturer' => 'Toyota','name' => 'Land Cruiser Prado'],
            ['manufacturer' => 'Toyota','name' => 'Mark II'],
            ['manufacturer' => 'Toyota','name' => 'Mirai'],
            ['manufacturer' => 'Toyota','name' => 'MR2'],
            ['manufacturer' => 'Toyota','name' => 'Picnic'],
            ['manufacturer' => 'Toyota','name' => 'Previa'],
            ['manufacturer' => 'Toyota','name' => 'Prius'],
            ['manufacturer' => 'Toyota','name' => 'RAV4'],
            ['manufacturer' => 'Toyota','name' => 'Sequoia'],
            ['manufacturer' => 'Toyota','name' => 'Sienna'],
            ['manufacturer' => 'Toyota','name' => 'Supra'],
            ['manufacturer' => 'Toyota','name' => 'Tacoma'],
            ['manufacturer' => 'Toyota','name' => 'Tundra'],
            ['manufacturer' => 'Toyota','name' => 'Venza'],
            ['manufacturer' => 'Toyota','name' => 'Verso'],
            ['manufacturer' => 'Toyota','name' => 'Vitz'],
            ['manufacturer' => 'Toyota','name' => 'Yaris'],
            ['manufacturer' => 'Toyota','name' => 'Yaris Verso'],
            ['manufacturer' => 'UAZ','name' => 'Pickup'],
            ['manufacturer' => 'UAZ','name' => 'Патриот'],
            ['manufacturer' => 'UAZ','name' => 'Хантер'],
            ['manufacturer' => 'VAZ','name' => '2101-2107'],
            ['manufacturer' => 'VAZ','name' => '2108, 2109, 21099'],
            ['manufacturer' => 'VAZ','name' => '2110, 2111, 2112'],
            ['manufacturer' => 'VAZ','name' => '2113, 2114, 2115'],
            ['manufacturer' => 'VAZ','name' => 'Granta'],
            ['manufacturer' => 'VAZ','name' => 'Largus'],
            ['manufacturer' => 'VAZ','name' => 'Largus Cross'],
            ['manufacturer' => 'VAZ','name' => 'Vesta Cross'],
            ['manufacturer' => 'VAZ','name' => 'Vesta Sport'],
            ['manufacturer' => 'VAZ','name' => 'Vesta SW'],
            ['manufacturer' => 'VAZ','name' => 'XRay'],
            ['manufacturer' => 'VAZ','name' => 'XRay Cross'],
            ['manufacturer' => 'VAZ','name' => 'Веста'],
            ['manufacturer' => 'VAZ','name' => 'Калина'],
            ['manufacturer' => 'VAZ','name' => 'Нива 4X4'],
            ['manufacturer' => 'VAZ','name' => 'Ока'],
            ['manufacturer' => 'VAZ','name' => 'Приора'],
            ['manufacturer' => 'Volkswagen','name' => 'Amarok'],
            ['manufacturer' => 'Volkswagen','name' => 'Arteon'],
            ['manufacturer' => 'Volkswagen','name' => 'Beetle'],
            ['manufacturer' => 'Volkswagen','name' => 'Bora'],
            ['manufacturer' => 'Volkswagen','name' => 'Caddy'],
            ['manufacturer' => 'Volkswagen','name' => 'CC'],
            ['manufacturer' => 'Volkswagen','name' => 'Crafter'],
            ['manufacturer' => 'Volkswagen','name' => 'CrossGolf'],
            ['manufacturer' => 'Volkswagen','name' => 'CrossPolo'],
            ['manufacturer' => 'Volkswagen','name' => 'CrossTouran'],
            ['manufacturer' => 'Volkswagen','name' => 'Eos'],
            ['manufacturer' => 'Volkswagen','name' => 'Fox'],
            ['manufacturer' => 'Volkswagen','name' => 'Golf'],
            ['manufacturer' => 'Volkswagen','name' => 'Jetta'],
            ['manufacturer' => 'Volkswagen','name' => 'Lupo'],
            ['manufacturer' => 'Volkswagen','name' => 'Multivan'],
            ['manufacturer' => 'Volkswagen','name' => 'New Beetle'],
            ['manufacturer' => 'Volkswagen','name' => 'Passat'],
            ['manufacturer' => 'Volkswagen','name' => 'Passat CC'],
            ['manufacturer' => 'Volkswagen','name' => 'Phaeton'],
            ['manufacturer' => 'Volkswagen','name' => 'Pointer'],
            ['manufacturer' => 'Volkswagen','name' => 'Polo'],
            ['manufacturer' => 'Volkswagen','name' => 'Routan'],
            ['manufacturer' => 'Volkswagen','name' => 'Scirocco'],
            ['manufacturer' => 'Volkswagen','name' => 'Sharan'],
            ['manufacturer' => 'Volkswagen','name' => 'T-Roc'],
            ['manufacturer' => 'Volkswagen','name' => 'Teramont'],
            ['manufacturer' => 'Volkswagen','name' => 'Tiguan'],
            ['manufacturer' => 'Volkswagen','name' => 'Touareg'],
            ['manufacturer' => 'Volkswagen','name' => 'Touran'],
            ['manufacturer' => 'Volkswagen','name' => 'Transporter'],
            ['manufacturer' => 'Volkswagen','name' => 'Up'],
            ['manufacturer' => 'Volvo','name' => 'C30'],
            ['manufacturer' => 'Volvo','name' => 'C70'],
            ['manufacturer' => 'Volvo','name' => 'C70 Convertible'],
            ['manufacturer' => 'Volvo','name' => 'C70 Coupe'],
            ['manufacturer' => 'Volvo','name' => 'S40'],
            ['manufacturer' => 'Volvo','name' => 'S60'],
            ['manufacturer' => 'Volvo','name' => 'S70'],
            ['manufacturer' => 'Volvo','name' => 'S80'],
            ['manufacturer' => 'Volvo','name' => 'S90'],
            ['manufacturer' => 'Volvo','name' => 'V40'],
            ['manufacturer' => 'Volvo','name' => 'V50'],
            ['manufacturer' => 'Volvo','name' => 'V60'],
            ['manufacturer' => 'Volvo','name' => 'V70'],
            ['manufacturer' => 'Volvo','name' => 'V90'],
            ['manufacturer' => 'Volvo','name' => 'XC40'],
            ['manufacturer' => 'Volvo','name' => 'XC60'],
            ['manufacturer' => 'Volvo','name' => 'XC70'],
            ['manufacturer' => 'Volvo','name' => 'XC90'],
        ];

        foreach ($models as $model) {
            $manufacturer = CarManufacturer::firstOrCreate(['name' => $model['manufacturer']]);

            \App\CarModel::create(['manufacturer_id' => $manufacturer->id, 'name' => $model['name']]);
        }
    }
}
